### ISSUE TITLE
Latest Commit working but with one issue

### ISSUE THREAD

**Issue by blind0wl** [Slut/TacStats#1]
/stats displaying correctly...still not sure what KDA stands for unless you use another term other than KDR.

/stats <player name> doesnt display because 

`var target = covalence.Players.FindPlayerById(args[0]);`

wants a steamid instead of a name.

Wish I knew the Oxide API better, have some experience with coding and would like to actually help rather than point at issues.

Cheers Again!

**Comment by Slut** [comment]
Fixed!
